CREATE TABLE IF NOT EXISTS cost_import_batch (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    batch_no VARCHAR(64) NOT NULL COMMENT '批次号，业务唯一',
    project_name VARCHAR(255) DEFAULT NULL COMMENT '项目名称/任务名称',
    source_type VARCHAR(32) DEFAULT NULL COMMENT '来源类型，如 tender/bid/manual',
    source_file_name VARCHAR(255) DEFAULT NULL COMMENT '源文件名',
    import_status VARCHAR(32) DEFAULT 'INIT' COMMENT '导入状态',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_batch_no (batch_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导入批次表';

CREATE TABLE IF NOT EXISTS cost_single_project (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    batch_id BIGINT NOT NULL COMMENT '归属批次',
    seq_no INT NOT NULL COMMENT '序号',
    single_project_name VARCHAR(255) NOT NULL COMMENT '单项工程名称',
    single_project_cost DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '单项工程造价',
    division_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '分部分项合计',
    measure_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '措施项目合计',
    other_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '其他项目合计',
    regulation_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '规费合计',
    fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '费用合计',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税金合计',
    total_measure_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总价措施项目合计',
    safe_civilized_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '安全文明施工费合计',
    provisional_sum_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂列金额合计',
    material_provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料暂估价合计',
    specialty_provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '专业工程暂估价合计',
    labor_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '人工费合计',
    material_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料费合计',
    machine_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '机械费合计',
    equipment_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '设备费合计',
    management_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '管理费合计',
    profit_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '利润合计',
    risk_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '风险费合计',
    construction_scale DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '建设规模',
    construction_scale_unit VARCHAR(32) DEFAULT NULL COMMENT '建设规模单位（可空，导入阶段允许缺失）',
    single_project_category_code VARCHAR(32) DEFAULT NULL COMMENT '单项工程分类编码（可空，导入阶段允许缺失）',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_batch_seq_no (batch_id, seq_no),
    KEY idx_batch_id (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单项工程基本信息表';

CREATE TABLE IF NOT EXISTS cost_single_project_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    single_project_id BIGINT NOT NULL COMMENT '单项工程ID',
    attr_name VARCHAR(128) NOT NULL COMMENT '名称',
    attr_value TEXT NOT NULL COMMENT '内容',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_single_profile (single_project_id, attr_name),
    KEY idx_single_project_id (single_project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单项工程概况信息表';

CREATE TABLE IF NOT EXISTS cost_single_project_extra (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    single_project_id BIGINT NOT NULL COMMENT '单项工程ID',
    attr_name VARCHAR(128) NOT NULL COMMENT '名称',
    attr_value TEXT NOT NULL COMMENT '内容',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_single_extra (single_project_id, attr_name),
    KEY idx_single_project_id (single_project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单项工程附加信息表';

CREATE TABLE IF NOT EXISTS cost_unit_project (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    single_project_id BIGINT NOT NULL COMMENT '单项工程ID',
    unit_project_code VARCHAR(64) NOT NULL COMMENT '单位工程编码',
    unit_project_name VARCHAR(255) NOT NULL COMMENT '单位工程名称',
    unit_project_cost DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '单位工程造价',
    specialty_category VARCHAR(64) NOT NULL COMMENT '专业类别',
    level3_metric_code VARCHAR(32) DEFAULT NULL COMMENT '三级指标分类编码（可空，导入阶段允许缺失）',
    division_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '分部分项合计',
    measure_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '措施项目合计',
    other_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '其他项目合计',
    safe_civilized_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '安全文明施工费合计',
    regulation_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '规费合计',
    fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '费用合计',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税金合计',
    total_measure_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总价措施项目合计',
    provisional_sum_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂列金额合计',
    material_provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料暂估价合计',
    specialty_provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '专业工程暂估价合计',
    labor_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '人工费合计',
    material_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料费合计',
    machine_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '机械费合计',
    equipment_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '设备费合计',
    management_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '管理费合计',
    profit_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '利润合计',
    risk_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '风险费合计',
    professional_type_code VARCHAR(32) DEFAULT NULL COMMENT '专业类型编码（可空，导入阶段允许缺失）',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_single_unit_code (single_project_id, unit_project_code),
    KEY idx_single_project_id (single_project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单位工程基本信息表';

CREATE TABLE IF NOT EXISTS cost_unit_project_extra (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    unit_project_id BIGINT NOT NULL COMMENT '单位工程ID',
    attr_name VARCHAR(128) NOT NULL COMMENT '名称',
    attr_value TEXT NOT NULL COMMENT '内容',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_unit_extra (unit_project_id, attr_name),
    KEY idx_unit_project_id (unit_project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单位工程附加信息表';

CREATE TABLE IF NOT EXISTS cost_division (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    unit_project_id BIGINT NOT NULL COMMENT '单位工程ID',
    division_code VARCHAR(64) NOT NULL COMMENT '分部工程编号',
    division_name VARCHAR(255) NOT NULL COMMENT '分部工程名称',
    level4_metric_code VARCHAR(32) DEFAULT NULL COMMENT '四级指标分类编码（可空，导入阶段允许缺失）',
    division_total_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '分部工程合计',
    provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂估价合计',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_unit_division_code (unit_project_id, division_code),
    KEY idx_unit_project_id (unit_project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分部分项信息表';

CREATE TABLE IF NOT EXISTS cost_boq_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    division_id BIGINT NOT NULL COMMENT '分部分项ID',
    seq_no INT NOT NULL COMMENT '序号',
    item_code VARCHAR(64) NOT NULL COMMENT '项目编码',
    item_name VARCHAR(255) NOT NULL COMMENT '项目名称',
    item_feature_desc TEXT NOT NULL COMMENT '项目特征描述',
    measure_unit VARCHAR(32) NOT NULL COMMENT '计量单位',
    quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '工程量',
    composite_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '综合单价',
    composite_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '综合合价',
    labor_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '人工费单价',
    material_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料费单价',
    machine_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '机械费单价',
    management_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '管理费单价',
    profit_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '利润单价',
    risk_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '风险费单价',
    total_measure_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总价措施单价',
    regulation_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '规费单价',
    fee_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '费用单价',
    tax_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税金单价',
    labor_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '人工费合价',
    material_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料费合价',
    machine_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '机械费合价',
    management_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '管理费合价',
    profit_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '利润合价',
    risk_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '风险费合价',
    total_measure_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总价措施合价',
    regulation_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '规费合价',
    fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '费用合价',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税金合价',
    professional_type_code VARCHAR(32) NOT NULL COMMENT '专业类型编码',
    unpriced_material_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '未计价材料合价',
    labor_unit_price_desc TEXT NOT NULL COMMENT '人工单价描述',
    provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂估合价',
    level5_metric_code VARCHAR(32) DEFAULT NULL COMMENT '五级指标分类编码（可空，导入阶段允许缺失）',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    UNIQUE KEY uk_division_seq_no (division_id, seq_no),
    KEY idx_division_id (division_id),
    KEY idx_item_code (item_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分部分项工程量清单与计价表';

CREATE TABLE IF NOT EXISTS cost_boq_item_quota (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    boq_item_id BIGINT NOT NULL COMMENT '清单项ID',
    quota_code VARCHAR(64) NOT NULL COMMENT '定额编号',
    quota_name VARCHAR(255) NOT NULL COMMENT '定额名称',
    quota_unit VARCHAR(32) NOT NULL COMMENT '定额单位',
    quantity DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '数量',
    labor_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '人工费单价',
    material_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料费单价',
    machine_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '机械费单价',
    management_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '管理费单价',
    profit_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '利润单价',
    risk_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '风险费单价',
    total_measure_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总价措施单价',
    regulation_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '规费单价',
    fee_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '费用单价',
    tax_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税金单价',
    composite_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '综合单价',
    composite_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '综合合价',
    labor_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '人工费合价',
    material_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '材料费合价',
    machine_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '机械费合价',
    management_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '管理费合价',
    profit_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '利润合价',
    risk_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '风险费合价',
    total_measure_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '总价措施合价',
    regulation_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '规费合价',
    fee_total_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '费用总价',
    tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '税金合价',
    unpriced_material_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '未计价材料合价',
    provisional_unit_price DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂估单价',
    provisional_amount DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '暂估合价',
    professional_type_code VARCHAR(32) NOT NULL COMMENT '专业类型编码',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    KEY idx_boq_item_id (boq_item_id),
    KEY idx_quota_code (quota_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分部分项工程量清单项目子目组价表';

CREATE TABLE IF NOT EXISTS cost_resource_summary (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    batch_id BIGINT NOT NULL COMMENT '批次ID',
    resource_type VARCHAR(32) NOT NULL COMMENT '资源类型：material/labor/machine/equipment/other',
    resource_code VARCHAR(64) DEFAULT NULL COMMENT '工料机编码',
    resource_name VARCHAR(255) NOT NULL COMMENT '工料机名称',
    resource_unit VARCHAR(32) DEFAULT NULL COMMENT '单位',
    unit_price DECIMAL(18,2) DEFAULT NULL COMMENT '单价（可选）',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    KEY idx_batch_id (batch_id),
    KEY idx_resource_code (resource_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工料机汇总表';

CREATE TABLE IF NOT EXISTS cost_quota_resource_usage (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    quota_id BIGINT NOT NULL COMMENT '子目组价ID',
    resource_summary_id BIGINT NOT NULL COMMENT '汇总材料ID/工料机ID',
    consumption_quota_content DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT '消耗量定额含量',
    consumption_adjust_coef DECIMAL(18,6) NOT NULL DEFAULT 1 COMMENT '消耗量定额含量调整系数',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    KEY idx_quota_id (quota_id),
    KEY idx_resource_summary_id (resource_summary_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工料机含量表';
